# Generated by Django 4.2.7 on 2024-04-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='user',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='user',
            new_name='user1',
        ),
    ]
