# Generated by Django 4.2.7 on 2024-04-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0002_rename_user_demand_user1_rename_name_medicine_name1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='user1',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='name1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='user1',
            new_name='user',
        ),
    ]
